<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tP_IDM" nsURI="http://www.example.org/tP_IDM" nsPrefix="tP_IDM">
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="Forward"/>
    <eLiterals name="Backward" value="1"/>
    <eLiterals name="Left" value="2"/>
    <eLiterals name="Right" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensRotation">
    <eLiterals name="Clock"/>
    <eLiterals name="CounterClock" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movement" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrique" eType="#//Metrique"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sens" eType="#//SensRotation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degre" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrique" eType="#//Metrique"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationBinaire" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Instruction">
    <eOperations name="evaluate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationUnaire" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloc" upperBound="-1" eType="#//Instruction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionArret" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefVariable" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valeur" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Metrique" abstract="true" interface="true"
      eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Centimeter" eSuperTypes="#//Metrique"/>
  <eClassifiers xsi:type="ecore:EClass" name="Meter" eSuperTypes="#//Metrique"/>
  <eClassifiers xsi:type="ecore:EClass" name="Millimeter" eSuperTypes="#//Metrique"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloc" upperBound="-1" eType="#//Instruction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefFonction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloc" upperBound="-1" eType="#//Instruction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsultVariable" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defvariable" eType="#//DefVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eOperations name="getTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Time"/>
    <eOperations name="setSpeed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="speed" eType="#//Speed"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constante" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetSpeed" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrique" eType="#//Metrique"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="getTimestamp" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallFonction" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//DefFonction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Times" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Divide" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inverse" eSuperTypes="#//OperationUnaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//OperationUnaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoreThan" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessThan" eSuperTypes="#//OperationBinaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equal" eSuperTypes="#//OperationBinaire"/>
</ecore:EPackage>
