/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class B0tchProposalProvider extends AbstractB0tchProposalProvider {
}
