/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class B0tchAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/botch/parser/antlr/internal/InternalB0tch.tokens");
	}
}
