/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.botch.parser.antlr.internal.InternalB0tchParser;
import org.xtext.example.botch.services.B0tchGrammarAccess;

public class B0tchParser extends AbstractAntlrParser {

	@Inject
	private B0tchGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalB0tchParser createParser(XtextTokenStream stream) {
		return new InternalB0tchParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Add";
	}

	public B0tchGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(B0tchGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
