/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.botch.ui.internal.BotchActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class B0tchExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BotchActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BotchActivator activator = BotchActivator.getInstance();
		return activator != null ? activator.getInjector(BotchActivator.ORG_XTEXT_EXAMPLE_BOTCH_B0TCH) : null;
	}

}
