/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.ide;


/**
 * Use this class to register ide components.
 */
public class B0tchIdeModule extends AbstractB0tchIdeModule {
}
