/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.botch.B0tchRuntimeModule;
import org.xtext.example.botch.B0tchStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class B0tchIdeSetup extends B0tchStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new B0tchRuntimeModule(), new B0tchIdeModule()));
	}
	
}
