/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractB0tchScopeProvider extends DelegatingScopeProvider {
}
