/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class B0tchUiModule extends AbstractB0tchUiModule {

	public B0tchUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
