/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.botch;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class B0tchStandaloneSetup extends B0tchStandaloneSetupGenerated {

	public static void doSetup() {
		new B0tchStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
